# Generated by Django 5.2.11 on 2026-03-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_autor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['id'], 'verbose_name': 'autor', 'verbose_name_plural': 'autores'},
        ),
    ]
